# SciKit Learn Prepocessing

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
data = np.random.randint(0,100,(10,2)) # 0 - 100, 10 rows 2 columns

In [4]:
data

array([[29, 82],
       [98, 13],
       [13, 61],
       [84, 56],
       [70, 84],
       [79, 97],
       [76, 23],
       [19, 47],
       [62, 91],
       [37, 78]])

In [7]:
scaler_model = MinMaxScaler()

In [8]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [9]:
scaler_model.fit(data)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [10]:
scaler_model.transform(data)

array([[0.45238095, 0.        ],
       [0.57142857, 0.73684211],
       [0.36904762, 0.73684211],
       [0.14285714, 1.        ],
       [1.        , 0.98684211],
       [0.11904762, 0.46052632],
       [0.55952381, 0.30263158],
       [0.36904762, 0.80263158],
       [0.        , 0.76315789],
       [0.88095238, 0.42105263]])

In [11]:
scaler_model.fit_transform(data)

/usr/local/lib/python3.5/dist-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.45238095, 0.        ],
       [0.57142857, 0.73684211],
       [0.36904762, 0.73684211],
       [0.14285714, 1.        ],
       [1.        , 0.98684211],
       [0.11904762, 0.46052632],
       [0.55952381, 0.30263158],
       [0.36904762, 0.80263158],
       [0.        , 0.76315789],
       [0.88095238, 0.42105263]])

In [12]:
import pandas as pd

In [15]:
mydata = np.random.randint(0,101,(50,4))

In [16]:
mydata

array([[ 71,  78,  82,   4],
       [  5,  77,  11,  61],
       [ 91,  59,  22,  37],
       [ 30,  32,   7,   4],
       [ 36,  85,  98,  94],
       [ 80,  55,  32,  70],
       [ 49,  65,  34,  60],
       [ 14,  20,  84,  99],
       [ 82,  27,  32,  42],
       [ 55,  57,  96,  73],
       [ 24,  87,  40,  25],
       [  2,  76,  39,  69],
       [ 82,  99,   2,  33],
       [ 47,  93,  41,   4],
       [ 12,  70,  71,  97],
       [ 90,  93,  36,  64],
       [ 59,  38,  89,   4],
       [ 88,  92,  75,  27],
       [ 38,  92,  54,  57],
       [ 39,  18,  55,  68],
       [ 64,  29,   3,  87],
       [ 83,  36,   7,  73],
       [ 87,  53,  64,  77],
       [ 57,  31,  94,  11],
       [100,  12,  44,   1],
       [ 33,  36,  94,  93],
       [ 46,   8,  69,  66],
       [ 33,  60,  70,  14],
       [ 12,  55,  83,  26],
       [  6,  11,  81,  38],
       [ 33,  48,  30,   5],
       [ 31,  13,  21,   0],
       [ 39, 100,  85,  72],
       [ 83,  75,  78,  56],
       [ 82,  

In [22]:
df = pd.DataFrame(data=mydata,columns = ['f1', 'f2', 'f3', 'label'])

In [23]:
df

f1   f2  f3  label
0    71   78  82      4
1     5   77  11     61
2    91   59  22     37
3    30   32   7      4
4    36   85  98     94
5    80   55  32     70
6    49   65  34     60
7    14   20  84     99
8    82   27  32     42
9    55   57  96     73
10   24   87  40     25
11    2   76  39     69
12   82   99   2     33
13   47   93  41      4
14   12   70  71     97
15   90   93  36     64
16   59   38  89      4
17   88   92  75     27
18   38   92  54     57
19   39   18  55     68
20   64   29   3     87
21   83   36   7     73
22   87   53  64     77
23   57   31  94     11
24  100   12  44      1
25   33   36  94     93
26   46    8  69     66
27   33   60  70     14
28   12   55  83     26
29    6   11  81     38
30   33   48  30      5
31   31   13  21      0
32   39  100  85     72
33   83   75  78     56
34   82   14  74     46
35   17   88  18     39
36   96   64  23     38
37   33   28  94     69
38   11   73  20     70
39   27   68  88     29
40   85   55  33     18
41   80   36   1     62
42  100   33  85     53
43   63   64  25     97
44   15   44  85     62
45   97   67  34     74
46   61   27  96     67
47   31   29  25     36
48   72   73   7     35
49   54    8  58     13

In [24]:
X = data[['f1', 'f2', 'f3']]

In [27]:
y = df['label']

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [32]:
X_train.shape

(35, 3)

In [34]:
X_test.shape

(15, 3)