## Reshape (Boyut Değiştirme)

In [1]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.arange(1,10).reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [3]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a = np.array([1,2,3])

In [5]:
a # tek boyutlu

array([1, 2, 3])

In [6]:
b = a.reshape((1,3))

In [7]:
b.ndim

2

In [8]:
a[np.newaxis, :] # iki boyutlu satır vektörü

array([[1, 2, 3]])

In [9]:
a[:, np.newaxis] # iki boyutlu sütun vektörü

array([[1],
       [2],
       [3]])