# Array Sıralama

In [1]:
import numpy as np
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [2]:
np.sort(v)
v

array([2, 1, 4, 3, 5])

In [3]:
v.sort()
v

array([1, 2, 3, 4, 5])

In [4]:
v = np.array([2, 1, 4, 3, 5])

In [5]:
i = np.argsort(v) # index'in sıralama sonrası nereye gittiği görüntülenir

In [6]:
i # 2->1 ve 1->0 index'e gittiği görülür

array([1, 0, 3, 2, 4])

In [7]:
v

array([2, 1, 4, 3, 5])

In [8]:
v[i] # sıralanmış halini elde ederiz

array([1, 2, 3, 4, 5])